<a href="https://colab.research.google.com/github/rakshal123/Introduction-To-Tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction To Tensors

In [1]:
#import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.4.1


In [2]:
# Creating tensors with tf.constants()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check number of dimensions of a tensor(ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
vector.ndim

1

In [6]:
# Create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# Create another matrix with dtype
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],[8.,9.]],dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# what is number of dimensions of another_matrix
another_matrix.ndim

2

In [10]:
# Lets create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]],[[14,15,16],[17,18,19]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]],

       [[14, 15, 16],
        [17, 18, 19]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've done so far:
* Scalar a single number
* Vector: a number with direction(wind speed and direction)
* Matrix: a 2-diensional array of numbers
* Tensor: an n_dimensional array of numbers(0 dimensional array is a scalar,1 dimensional array is a vector)

### Creating Tensor with 'tf.Variable'

In [12]:
changeable_tensor = tf.Variable([10,8,5,6,8,9])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([10,  8,  5,  6,  8,  9], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Changing the value of a tensor using '.assign' keyword
changeable_tensor[0:2].assign([10,7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([10,  7,  5,  6,  8,  9], dtype=int32)>

In [14]:
# This '.assign' keyword doesnot work on unchangeable tensor

# Creating random tensors
Random tensors are tensors of some arbitrary size which contains random numbers

In [15]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
# Are the equal
random_1,random_2,random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [16]:
## Shuffle a tensor 
not_shuffle = tf.constant([[10,7],
                           [3,4],
                           [2,5]])



In [17]:
# Shuffle out not_shuffle
tf.random.set_seed(42) #global level random seed
tf.random.shuffle(not_shuffle,seed = 67)#operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [18]:
not_shuffle.ndim

2

### Other ways to make Tensors

In [19]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [20]:
# Create a zero tensor
tf.zeros([3,4],dtype='int32')

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)>

### Turn NumPy into tensors

The main difference between Numpy and Tensors is that Tensor can be run on a "GPU" which is useful for fast computing

In [21]:
# you can also turn NumPy arrays int tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32)
numpy_A


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [22]:
A = tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

### Getting Information From Tensor
When dealing with Tensors we need to take care of these for attributes first:
* Shape
* Rank
* Axis or Dimension
* Size

In [23]:
# Create a rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [24]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [25]:
rank_4_tensor.shape,rank_4_tensor.ndim,tf.size(rank_4_tensor).numpy()

(TensorShape([2, 3, 4, 5]), 4, 120)

In [26]:
print("Element along the zero axis:",rank_4_tensor.shape[0])
print("Element along the last Axis:",rank_4_tensor.shape[-1])

Element along the zero axis: 2
Element along the last Axis: 5


### Indexing Tensors
Tensors can be indexed just like Python Lists

In [27]:
# Get the forst two elements of each dimensions
rank_4_tensor[:1,:,:3,:4]

<tf.Tensor: shape=(1, 3, 3, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
# Create a rank 2 tensor(2 dimmension)

rank_2_tensor = tf.constant([[10,7],
                             [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [29]:
# Last item of each our rank 2 Tensor
rank_2_tensor[:,-1].numpy()

array([7, 4], dtype=int32)

In [30]:
# Add Extra dimension in rank 2 tensor

rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [31]:
#Alternative to tf.newaxis is using tf.expand_dims

tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

#Manipulating Tensors(Tensor operations)

**Basic Operations**

**+** , **-** , **/** , **X**

In [32]:
# You can add values to a tensor

tensor = tf.constant([[10,7],[10,2]])
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [20, 12]], dtype=int32)>

In [33]:
#Multiplication also works
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [100,  20]], dtype=int32)>

In [34]:
# We can use the tensorflow built-in functions

tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [100,  20]], dtype=int32)>

In [35]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [20, 12]], dtype=int32)>

### Matrix Multiplication
Using the function **tf.matmul**

In [36]:
tensor.numpy(),tf.matmul(tensor,tensor).numpy()

(array([[10,  7],
        [10,  2]], dtype=int32), array([[170,  84],
        [120,  74]], dtype=int32))

In [37]:
tensor_1 = tf.constant([[1,2,5],[7,2,1],[3,3,3]])
tensor_2 = tf.constant([[3,5],[6,7],[1,8]])
tf.matmul(tensor_1,tensor_2,transpose_a=True)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[48, 78],
       [21, 48],
       [24, 56]], dtype=int32)>

In [38]:
tensor_1 @ tensor_2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [39]:
# Let's change the shape of the tensor

tf.reshape(tensor_1,shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 5],
       [7, 2, 1],
       [3, 3, 3]], dtype=int32)>

### Changing the datatypes of the Tensors

In [40]:
B = tf.constant([1.7,6.5])
B.dtype

tf.float32

In [41]:
#The Precision default is 32-bit but we can change it to 16-bit for faster processing
# to change from float32 to float16
B = tf.cast(B,dtype = tf.float16)
B.dtype

tf.float16

In [42]:
C = tf.constant([1,7])
C.dtype

tf.int32

In [43]:
# to convert tf.int32 to tf.float32 we can
C = tf.cast(C,dtype=tf.float32)
C.dtype

tf.float32

### Aggregationg Tensors

Aggregating Tensors = condensing them from multiple values down to a smaller amount of values.

In [44]:
# Get the absolute value
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [45]:
# Ge the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

# Lets Go through different forms of aggregation

* Find the minimum
* Get the maximum
* Get the mean of the Tensor
* Get the sum of the Tensor
* Get the Variance and Standard Deviation

[link text](https://www.tensorflow.org/api_docs/python/tf/math/reduce_variance)

In [46]:
# Creating a Tensor
E = tf.constant(np.random.randint(0,100,100))
E= tf.reshape(E,shape=(2,5,10))
E

<tf.Tensor: shape=(2, 5, 10), dtype=int64, numpy=
array([[[55, 33,  9, 53, 30, 54, 83, 13, 15, 24],
        [31, 30,  2, 92, 74, 27, 55, 98, 89,  6],
        [73, 71, 92, 37, 55, 61, 46, 44, 97, 22],
        [ 8, 58, 29, 43, 45,  0, 21, 42, 47, 72],
        [73, 83, 66, 58, 62, 38, 53, 16,  2, 66]],

       [[89, 27, 61, 55,  4,  2, 92, 39, 25, 84],
        [74, 99, 98, 85, 91, 65, 32, 40, 42, 47],
        [31, 93, 15,  9,  3, 12, 54, 25, 72, 71],
        [90, 32, 32, 45,  6, 12, 38, 59, 84, 63],
        [55, 32, 60, 61, 26, 73, 81, 13, 15, 39]]])>

In [47]:
#Find the minimum

tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [48]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [49]:
# Get the mean of the Tensor
tf.reduce_mean(E,axis=0)

<tf.Tensor: shape=(5, 10), dtype=int64, numpy=
array([[72, 30, 35, 54, 17, 28, 87, 26, 20, 54],
       [52, 64, 50, 88, 82, 46, 43, 69, 65, 26],
       [52, 82, 53, 23, 29, 36, 50, 34, 84, 46],
       [49, 45, 30, 44, 25,  6, 29, 50, 65, 67],
       [64, 57, 63, 59, 44, 55, 67, 14,  8, 52]])>

In [50]:
#Get the sum of the Tensor
tf.reduce_sum(E,axis=2),E.ndim

(<tf.Tensor: shape=(2, 5), dtype=int64, numpy=
 array([[369, 504, 598, 365, 517],
        [478, 673, 385, 461, 455]])>, 3)

In [51]:
 # Get the Variance and Standard Deviation
E = tf.cast(E,dtype=tf.float32)
tf.math.reduce_variance(E, axis=None, keepdims=False, name=None)

<tf.Tensor: shape=(), dtype=float32, numpy=784.8475>

### Find the positional maximum and minimum

In [52]:
# Create a new tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [53]:
# Find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [54]:
F[tf.argmax(F)]==tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [55]:
# Find the positional minimum
tf.argmin(F),F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

###Sqeezing a Tensor (Removing all the single dimensions)

In [56]:
# Create a tensor to get started
tf.random.set_seed(42)
D = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,2,1,25))
D

<tf.Tensor: shape=(1, 1, 2, 1, 25), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ]],

         [[0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [57]:
# to squeeze
D_squeezed = tf.squeeze(D)
D_squeezed,D_squeezed.shape

(<tf.Tensor: shape=(2, 25), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
         0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
         0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
         0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
         0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ],
        [0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
         0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
         0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
         0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
         0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]],
       dtype=float32)>, TensorShape([2, 25]))

### One Hot encoding Tensor
It is the form of numerical encoding

In [58]:
#Create a list of indices
some_list = [0,1,2,3]# could be red,green,blue,indigo

#One Hot Encode for our list of indices
tf.one_hot(some_list,depth=4).numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>>

### Squaring, Log and SquareRoots

In [60]:
#Create a new Tensor
H = tf.constant(tf.range(0,10),shape=(2,5))
H

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]], dtype=int32)>

In [61]:
# Square it
tf.square(H)

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]], dtype=int32)>

In [64]:
#Find the square Root(method require not int type dtype)
tf.sqrt(tf.cast(H,dtype=tf.float16))

<tf.Tensor: shape=(2, 5), dtype=float16, numpy=
array([[0.   , 1.   , 1.414, 1.732, 2.   ],
       [2.236, 2.45 , 2.646, 2.828, 3.   ]], dtype=float16)>

In [66]:
# Find the log
tf.math.log(tf.cast(H,dtype=tf.float16))

<tf.Tensor: shape=(2, 5), dtype=float16, numpy=
array([[  -inf, 0.    , 0.6934, 1.099 , 1.387 ],
       [1.609 , 1.792 , 1.946 , 2.08  , 2.197 ]], dtype=float16)>

### Tensors and Numpy

Tensor can very easily interact with Numpy

In [67]:
# Create a tensor using an numpy array
J = tf.constant(np.array([1.,2.,3.,4.,5.]))
J

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 2., 3., 4., 5.])>

In [69]:
# Convert a tensor back to Numpy array

np.array(J),J.numpy,type(np.array(J)),type(J.numpy())

(array([1., 2., 3., 4., 5.]),
 <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 2., 3., 4., 5.])>>,
 numpy.ndarray,
 numpy.ndarray)

In [71]:
# The default dtype of Numpy generated tensor and tensorflow generated tensor might be different
l=[1.,2.,3.,4.,5.]
numpy_J = tf.constant(np.array(l))
tensor_J = tf.constant(l)
# If we check the datatype(dtype) of both the values
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)